export const CAMPAIGN_STATUS_ALL: string="ALL";  
export const CAMPAIGN_STATUS_AWAITING_ACTIVATION: string="AWAITING_ACTIVATION"; 
export const CAMPAIGN_STATUS_ACTIVE: string="ACTIVE"; 
export const CAMPAIGN_STATUS_SUSPENDED: string="SUSPENDED";  
export const CAMPAIGN_STATUS_CLOSED: string="CLOSED"; 
